### ISSUE TITLE
UpSet plots show mismatch between number of units in title (e.g., n = 8/84) vs. number of units actually plotted

### ISSUE THREAD

**Issue by nikhilchandra** [Julie-Fabre/bombcell#336]
There is a mismatch between the number of units reported in the title of the UpSet plots vs. the number of units actually plotted. For example, in the plot below, the title indicates that there is exactly 1 non-somatic unit, but the plot shows that there are many more.

![Image](https://github.com/user-attachments/assets/f54e7481-cca0-4cdf-b7ac-bf2434913c34)

**Comment by Julie-Fabre** [comment]
Sorry about that, good catch! The full non-somatic logic was not implemented in thh upSet plot. Now [fixed](https://github.com/Julie-Fabre/bombcell/commit/777a33e2e8b49f86e4f53dbadae824633231ad52)

**Comment by nikhilchandra** [comment]
I tried out the latest code and now this is what I see. It looks to me like the upsetplot function "from_indicators" creates a multi-level index ONLY IF there is more than one column with True values, otherwise you get an error message when the plot command runs. Is this expected behavior? Maybe a good fix would be to replace len(noise_metrics), len(non_somatic_metrics), len(mua_metrics) from the IF statements that control plotting with something that reflects how many columns have True values?

![Image](https://github.com/user-attachments/assets/7d4ee2c8-c5f0-46a5-b40d-cec1e06628ef)

**Comment by Julie-Fabre** [comment]
That's definitely not expected behavior! Is it better now for you?

**Comment by mgpaletta** [comment]
Hello, I am also having the issue with the non-somatic upset plot stated above. Do we know yet what is causing this so I can fix it?

**Comment by Julie-Fabre** [comment]
Hi, 
Thanks for your message! I just pushed a change that should solve this. Could you have a check ? Thanks a lot!

**Comment by mgpaletta** [comment]
Hi Julie! I haven't yet been able to resolve this, I still get the same errors with the updates. Some possible culprits:

1. there are some areas where non-somatic units seem to be referred to with different labels... for instance, within plot_functions.py, I seem some areas where they are "NON-SOMATIC" and some where they are "NON-SOMA"
2. There also seems to be an issue in generate_upset_plot where unit_type_metrics for MUA is asking for some columns that don't exist in qm_table. Specifically, if you print unit_type_data once the unit type is indexed, you see only 6 columns print for MUA where there should be 9. "max. drift", "isolation dist.", and "L-ratio" are missing. If you print qm_table, you see it is producing an Index object (as was noted in the error message), and that object contains all of the columns requested to produce unit_type_metrics except the three that are missing for MUAs. This seems likely to be related...

I have to step away for a bit, but I'll return to this asap if you don't beat me to it and keep digging.

**Comment by Julie-Fabre** [comment]
Hi, 
I'm sorry to hear that! It's odd because I cannot reproduce these errors on my end. Are you 100% sure you're using the latest code? 
To answer your points (thanks for sending!):
1. that should not have been any issue (the line in question was unit_type_mask = qm_table['unit_type'].str.startswith("NON-SOMA") which will work if the label is "NON-SOMATIC"). Regardless, I have updated the code so the only label used in "NON-SOMA", this is nicer and fits the MATLAB version and doesn't affect backcompatibility.
2. This is normal: The missing columns ("max. drift", "isolation dist.", and "L-ratio") are only added to qm_table when the corresponding parameters are enabled:
  - "max. drift" requires param["computeDrift"] = True (default: False)
  - "isolation dist." and "L-ratio" require param["computeDistanceMetrics"] = True (default: False)
The generate_upset_plot function correctly handles this by filtering out uncomputed metrics on line 292. This is the expected behavior - metrics that weren't computed won't appear in the plot.

**Comment by nikhilchandra** [comment]
I'm opening a new issue for the Warning problem I described on July 2nd (see #355)
